// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnWqop2F2ElcXNx-AOJIEW86BAXzfc6MA',
    appId: '1:582812976622:web:f71734580b04721784faff',
    messagingSenderId: '582812976622',
    projectId: 'mifinapp-f8e10',
    authDomain: 'mifinapp-f8e10.firebaseapp.com',
    storageBucket: 'mifinapp-f8e10.firebasestorage.app',
    measurementId: 'G-MQH5KWKCZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hNILeUtpvyx7R9JpCIHJvvYm_7C1a64',
    appId: '1:582812976622:android:9f6db3f609e8055f84faff',
    messagingSenderId: '582812976622',
    projectId: 'mifinapp-f8e10',
    storageBucket: 'mifinapp-f8e10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTEPxglYFtgb6wverwzHSQ5yqfrD1mPkI',
    appId: '1:582812976622:ios:6b1f269c4fe5119b84faff',
    messagingSenderId: '582812976622',
    projectId: 'mifinapp-f8e10',
    storageBucket: 'mifinapp-f8e10.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTEPxglYFtgb6wverwzHSQ5yqfrD1mPkI',
    appId: '1:582812976622:ios:6b1f269c4fe5119b84faff',
    messagingSenderId: '582812976622',
    projectId: 'mifinapp-f8e10',
    storageBucket: 'mifinapp-f8e10.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnWqop2F2ElcXNx-AOJIEW86BAXzfc6MA',
    appId: '1:582812976622:web:a6d8e924978c3db384faff',
    messagingSenderId: '582812976622',
    projectId: 'mifinapp-f8e10',
    authDomain: 'mifinapp-f8e10.firebaseapp.com',
    storageBucket: 'mifinapp-f8e10.firebasestorage.app',
    measurementId: 'G-EG8THBFB6R',
  );
}
